# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# 직접 Flutter SDK 경로를 설정합니다.
flutter_root = '/Users/aiden/flutter'  # 여기를 실제 Flutter SDK 경로로 변경하세요.

# podhelper.rb 파일을 가져옵니다.
require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
